name: giid
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^8.1.0

  animated_splash_screen: ^1.3.0
  mongo_dart: ^0.7.4+1

  provider: ^6.0.3
  dio: ^4.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/hall1.jpeg
    - images/hall2.jpeg
    - images/hall3.jpeg
    - images/hall4.jpeg
    - images/hall5.jpeg
    - images/hall6.jpeg
    - images/theatre.jpeg
    - images/logo.png
    - images/splashbackground.png

